#!/usr/bin/env bash
# Install NGNINX an start service
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i 's/server_name _;/server_name _;\n\trewrite ^\/redirect_me http:\/\/ojotimilehin.xyz permanent;/' /etc/nginx/sites-available/default
service nginx start
