#!/usr/bin/env bash
# install nginx and redirect to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "30i \\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=oavMtUWDBTM;\n}" /etc/nginx/sites-available/default
sudo service nginx restart
