#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80

apt-get update
apt-get -y install nginx
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx start
